Django/Django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gvozdje.urls'))
]

Django/gvozdje/urls.py
from django.urls import path, include
from django.contrib import admin

from . import views

app_name = 'gvozdje'
urlpatterns = [

    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),

    path('', views.gvozdje, name='home'),
    path('user', views.userPage, name='userPage'),
    path('mreza', views.createMreza, name='Mreza'),
    path('gvozdje', views.createGvozdje, name='Gvozdje'),

    path('update_mreza/<int:mreza_id>/', views.updateMreza, name='UpdateM'),
    path('update_gvozdje/<int:gvozdje_id>/', views.updateGvozdje, name='UpdateG'),

    path('deleteMreza/<int:mreza_id>/', views.deleteMreza, name='DeleteM'),
    path('deleteGvozdje/<int:gvozdje_id>/', views.deleteGvozdje, name='DeleteG')

]

Django/projekat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('gvozdje.urls'))
]

Django/gvozdje/models.py
from django.db import models

# Create your models here.


class Gvozdje(models.Model):
    naziv = models.CharField(max_length=50)
    jedinicaMere = models.CharField(max_length=4)
    cena_DIN = models.IntegerField(default=0)

    def __str__(self):
        return self.naziv

class Mreza(models.Model):
    naziv = models.CharField(max_length=100)
    dimenzijeKocke = models.CharField(max_length=50)
    dimenzije = models.CharField(max_length=50)
    jedinicaMere = models.CharField(max_length=4)
    cena_DIN = models.IntegerField(default=0)
    proizvedeno_Od = models.ForeignKey(Gvozdje, on_delete = models.CASCADE)

    def __str__(self):
        return self.naziv

Django/gvozdje/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import *


class GvozdjeForm(ModelForm):
    class Meta:
        model = Gvozdje
        fields = '__all__'

class MrezaForm(ModelForm):
    class Meta:
        model = Mreza
        fields = '__all__'

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

Django/gvozdje/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template import loader
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group

from .decorators import unauthentificated_user, allow_users, admin_only
from .forms import *

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.decorators import login_required

from .models import *

@unauthentificated_user
def registerPage(request):
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                user = form.save()
                username = form.cleaned_data.get('username')

                group = Group.objects.get(name='customer')
                user.groups.add(group)

                messages.success(request, 'Account created for ' + username)

                return redirect('gvozdje:login')

        context = {'form':form}
        return render(request, 'gvozdje/register.html', context)

@unauthentificated_user
def loginPage(request):
        if request.method == 'POST':
           username = request.POST.get('username')
           password = request.POST.get('password')

           user = authenticate(request, username=username, password=password)

           if user is not None:
               login(request, user)
               return redirect('gvozdje:home')
           else:
               messages.info(request, 'Username or Password is incorect')

        context = {}
        return render(request, 'gvozdje/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('gvozdje:login')

@login_required(login_url='gvozdje:login')
@admin_only
def gvozdje(request):
    gvozdje = Gvozdje.objects.all()
    mreza = Mreza.objects.all()
    return render(request, 'gvozdje/dashboard.html', {'gvozdje': gvozdje, 'mreza': mreza})

def userPage(request):
    gvozdje = Gvozdje.objects.all()
    mreza = Mreza.objects.all()
    return render(request, 'gvozdje/user.html', {'gvozdje': gvozdje, 'mreza': mreza})

@login_required(login_url='gvozdje:login')
@allow_users(allowed_roles=['admin'])
def createMreza(request):
    form = MrezaForm()
    if request.method == 'POST':
        form = MrezaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            print(ValueError)

    context = {'form': form}

    return render(request, 'gvozdje/mreza.html', context)

@login_required(login_url='gvozdje:login')
@allow_users(allowed_roles=['admin'])
def createGvozdje(request):

    form = GvozdjeForm()
    if request.method == 'POST':
        form = GvozdjeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            print(ValueError)

    context = {'form':form}

    return render(request, 'gvozdje/gvozdje.html', context)

@login_required(login_url='gvozdje:login')
@allow_users(allowed_roles=['admin'])
def updateMreza(request, mreza_id):

    mreza = Mreza.objects.get(id = mreza_id)
    form = MrezaForm(instance=mreza)
    if request.method == "POST":
        form = MrezaForm(request.POST, instance=mreza)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            print(ValueError)


    context = {'form':form}
    return render(request, 'gvozdje/mreza.html', context)

@login_required(login_url='gvozdje:login')
@allow_users(allowed_roles=['admin'])
def updateGvozdje(request, gvozdje_id):

    gvozdje = Gvozdje.objects.get(id = gvozdje_id)
    form = GvozdjeForm(instance=gvozdje)
    if request.method == "POST":
        form = GvozdjeForm(request.POST, instance=gvozdje)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            print(ValueError)


    context = {'form':form}
    return render(request, 'gvozdje/gvozdje.html', context)

@login_required(login_url='gvozdje:login')
@allow_users(allowed_roles=['admin'])
def deleteMreza(request, mreza_id):
    mreza = Mreza.objects.get(id=mreza_id)
    if request.method == "POST":
        mreza.delete()
        return redirect('/')

    context = {'item': mreza}
    return  render(request, 'gvozdje/delete_mreza.html', context)

@login_required(login_url='gvozdje:login')
@allow_users(allowed_roles=['admin'])
def deleteGvozdje(request, gvozdje_id):

    gvozdje = Gvozdje.objects.get(id=gvozdje_id)

    if request.method == "POST":
        gvozdje.delete()
        return redirect('/')

    context = {'item': gvozdje}
    return  render(request, 'gvozdje/delete_gvozdje.html', context)

Django/gvozdje/templates/gvozdje/dashboard.html
{% extends 'gvozdje/main.html' %}

{% block content %}



<hr class = "row">

    <div class="col-md-5"></div>
    <h2>GVOZDJE:</h2>

    <hr>

    <div class="card card-body">
        <a class="btn btn-primary btn-sm btn-block" href="{% url 'gvozdje:Gvozdje' %}">Dodaj
        </a>
        <table class="table table-sm">
            <tr>
                <th></th>
                <th>naziv</th>
                <th>cena</th>
                <th>jedinica mere</th>
                <th>Update</th>
                <th>Remove</th>
            </tr>
            {% for i in gvozdje %}
            <tr>
                 <td></td>
                 <td>{{i.naziv}}</td>
                 <td>{{i.cena_DIN}}</td>
                 <td>{{i.jedinicaMere}}</td>
                 <td><a class="btn btn-sm btn-info" href="{% url 'gvozdje:UpdateG' i.id %}">Update</a> </td>
                 <td><a class="btn btn-sm btn-danger" href="{% url 'gvozdje:DeleteG' i.id %}">Delete</a> </td>

            </tr>


            {% endfor %}
        </table>
    </div>


    <div class="col-md-7"></div>
    <h2>MREZA:</h2>

    <hr>

    <div class = "card card-body">
        <a class = "btn btn-primary btn-sm btn-block" href="{% url 'gvozdje:Mreza' %}">Dodaj
        </a>
        <table class="table table-sm">
            <tr>
                <th></th>
                <th>naziv</th>
                <th>dimenzije</th>
                <th>dimenzije kocke</th>
                <th>jedinica mere</th>
                <th>dobijeno od</th>
                <th>cena</th>
                <th>Update</th>
                <th>Remove</th>
            </tr>

            {% for i in mreza %}
            <tr>
                 <td></td>
                 <td>{{i.naziv}}</td>
                 <td>{{i.dimenzije}}</td>
                 <td>{{i.dimenzijeKocke}}</td>
                 <td>{{i.jedinicaMere}}</td>
                 <td>{{i.proizvedeno_Od}}</td>
                 <td>{{i.cena_DIN}}</td>
                 <td><a class="btn btn-sm btn-info" href="{% url 'gvozdje:UpdateM' i.id %}">Update</a> </td>
                 <td><a class="btn btn-sm btn-danger" href="{% url 'gvozdje:DeleteM' i.id %}">Delete</a> </td>

            </tr>


            {% endfor %}
        </table>
    </div>


</div>

{% endblock %}

Django/gvozdje/templates/gvozdje/delete_gvozdje.html
{% extends 'gvozdje/main.html' %}

{% block content %}

<p>Da li ste sigurni da zelite da obrisete "{{item}}?"</p>

<form action="{% url 'gvozdje:DeleteG' item.id %}" method="POST">


    {% csrf_token %}
    <a class="btn btn-warning" href="{% url 'gvozdje:home' %}">Cancel</a>

    <input class="btn btn-danger" type="submit" name="Confirm">
</form>

{% endblock %}

Django/gvozdje/templates/gvozdje/delete_mreza.html
{% extends 'gvozdje/main.html' %}

{% block content %}

<p>Da li ste sigurni da zelite da obrisete "{{item}}?"</p>

<form action="{% url 'gvozdje:DeleteM' item.id %}" method="POST">


    {% csrf_token %}
    <a class="btn btn-warning"  href="{% url 'gvozdje:home' %}">Cancel</a>

    <input class="btn btn-danger"  type="submit" name="Confirm">
</form>

{% endblock %}

Django/gvozdje/templates/gvozdje/gvozdje.html
{% extends 'gvozdje/main.html' %}
{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" name="Submit">

</form>

{% endblock %}

Django/gvozdje/templates/gvozdje/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

                {% for message in messages %}
                    <p id="messages">{{message}}</p>
                {% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'gvozdje:register' %}" class="ml-2">Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>

</html>

Django/gvozdje/templates/gvozdje/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Radisic</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    {% include 'gvozdje/navbar.html' %}

    {% block content %}



    {% endblock %}

    <hr>
    <h5>Footer</h5>
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>

Django/gvozdje/templates/gvozdje/mreza.html
{% extends 'gvozdje/main.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" name="Submit">

</form>
{% endblock %}

Django/gvozdje/templates/gvozdje/navbar.html
<style>
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Dashboard</a>
      </li>
    </ul>
  </div>

  <span class="hello-msg">Hello, {{request.user}}</span>
  <span><a class="hello-msg" href="{% url 'gvozdje:logout' %}"> Logout</a></span>


</nav>

Django/gvozdje/templates/gvozdje/register.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>

                {{form.errors}}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'gvozdje:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

Django/gvozdje/templates/gvozdje/user.html
{% extends 'gvozdje/main.html' %}
{% block content %}

<hr class = "row">

    <div class="col-md-5"></div>
    <h2>GVOZDJE:</h2>

    <hr>

    <div class="card card-body">
        <table class="table table-sm">
            <tr>
                <th></th>
                <th>naziv</th>
                <th>cena</th>
                <th>jedinica mere</th>

            </tr>
            {% for i in gvozdje %}
            <tr>
                 <td></td>
                 <td>{{i.naziv}}</td>
                 <td>{{i.cena_DIN}}</td>
                 <td>{{i.jedinicaMere}}</td>

            </tr>


            {% endfor %}
        </table>
    </div>


    <div class="col-md-7"></div>
    <h2>MREZA:</h2>

    <hr>

    <div class = "card card-body">
        <table class="table table-sm">
            <tr>
                <th></th>
                <th>naziv</th>
                <th>dimenzije</th>
                <th>dimenzije kocke</th>
                <th>jedinica mere</th>
                <th>dobijeno od</th>
                <th>cena</th>

            </tr>

            {% for i in mreza %}
            <tr>
                 <td></td>
                 <td>{{i.naziv}}</td>
                 <td>{{i.dimenzije}}</td>
                 <td>{{i.dimenzijeKocke}}</td>
                 <td>{{i.jedinicaMere}}</td>
                 <td>{{i.proizvedeno_Od}}</td>
                 <td>{{i.cena_DIN}}</td>

            </tr>


            {% endfor %}
        </table>
    </div>


</div>

{% endblock %}